export { Slide00Cover } from './Slide00Cover';
export { Slide01ExecutiveSummary } from './Slide01ExecutiveSummary';
export { Slide02VisionThesis } from './Slide02VisionThesis';
export { Slide03CurrentState } from './Slide03CurrentState';
export { Slide04Transformation } from './Slide04Transformation';
export { Slide05InitialCapital } from './Slide05InitialCapital';
export { Slide06CaseStudy } from './Slide06CaseStudy';
export { Slide07Roadmap } from './Slide07Roadmap';
export { Slide08ExitStrategy } from './Slide08ExitStrategy';
